import { contextBridge, ipcRenderer, IpcRendererEvent } from 'electron'
import type {
  Api,
  CreateProjectInput,
  CreateRepoInput,
  UpdateProjectInput,
  UpdateRepoInput,
  ReorderReposInput,
  SpawnSessionInput,
  ResumeSessionInput,
  PtyDataEvent,
  PtyExitEvent,
  SessionActivity,
  GlobalActivityBatch,
  PaneSnapshot,
  UpdateStatus,
  UsageStatus,
  NotificationEvent,
  MetricsWindow,
  MetricsScanProgress,
  Feature,
  CreateFeatureInput,
  UpdateFeatureInput,
  SetFeatureReposInput,
  SetFeatureObjectiveLinksInput,
  FeatureSynthError,
  CreateRepoDependencyInput,
  UpdateRepoDependencyInput,
  SetRepoHubInput,
  ConnectHubToAllInput,
  AdoptSessionInput,
  CreateManualHandoffInput,
  HandoffOutcome,
  DistillBatonInput,
  PassBatonInput,
  HandoffStatus,
  CreateDossierApiInput,
  DossierPlanInput,
  DossierStatus,
  ObjectiveListFilter,
  CreateObjectiveInput,
  UpdateObjectiveInput,
  CreateKeyResultInput,
  UpdateKeyResultInput,
  TaskListFilter,
  TaskParentType,
  TaskLink,
  CreateTaskInput,
  UpdateTaskInput,
  ScheduledJobListFilter,
  CreateScheduledJobInput,
  UpdateScheduledJobInput,
  JobRunListFilter,
  JobSchedule,
  ContentContractListFilter,
  ContentGateRunListFilter,
  RunContentGateInput,
  UpsertContentContractInput,
  DiagramListFilter,
  DiagramLink,
  DiagramAuthor,
  CreateDiagramInput,
  UpdateDiagramSceneInput,
  MeetingListFilter,
  MeetingSegment,
  MeetingSpeaker,
  MeetingStatusEvent,
  MeetingPartialEvent,
  MeetingInstallLogEvent,
  MeetingInstallDoneEvent,
  MeetingActivationDraft,
  CreateMeetingInput,
  UpdateMeetingInput,
  MaterializeMeetingTaskInput,
  SetSpeakerNameInput,
  SyncConfigureInput,
  SyncResolveConflictInput,
  SyncSetProjectsRootInput,
  ChatTranscriptUpdate,
  McpAddInput,
  McpRemoveInput,
  VoiceSummaryEvent,
} from '../../shared/types/ipc'

const invoke = <T>(channel: string, ...args: unknown[]): Promise<T> =>
  ipcRenderer.invoke(channel, ...args) as Promise<T>

function subscribe<T>(
  channel: string,
  handler: (event: T) => void,
): () => void {
  const listener = (_e: IpcRendererEvent, payload: T) => handler(payload)
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}

const api: Api = {
  projects: {
    list: () => invoke('projects:list'),
    create: (input: CreateProjectInput) => invoke('projects:create', input),
    update: (input: UpdateProjectInput) => invoke('projects:update', input),
    delete: (id: string) => invoke('projects:delete', id),
    reorder: (ids: string[]) => invoke('projects:reorder', ids),
    listRepos: (projectId: string) => invoke('projects:repos:list', projectId),
    createRepo: (input: CreateRepoInput) => invoke('projects:repos:create', input),
    updateRepo: (input: UpdateRepoInput) => invoke('projects:repos:update', input),
    deleteRepo: (id: string) => invoke('projects:repos:delete', id),
    reorderRepos: (input: ReorderReposInput) => invoke('projects:repos:reorder', input),
    listAllRepos: () => invoke('projects:repos:list-all'),
  },
  sessions: {
    spawn: (input: SpawnSessionInput) => invoke('sessions:spawn', input),
    resume: (input: ResumeSessionInput) => invoke('sessions:resume', input),
    isResumable: (ccSessionId) => invoke('sessions:is-resumable', ccSessionId),
    listByRepo: (repoId) => invoke('sessions:list-by-repo', repoId),
    getBacklog: (sessionId) => invoke('sessions:get-backlog', sessionId),
    write: (sessionId, data) => invoke('sessions:write', sessionId, data),
    saveImage: (sessionId, bytes, mime) =>
      invoke('sessions:save-image', sessionId, bytes, mime),
    resize: (sessionId, cols, rows) => invoke('sessions:resize', sessionId, cols, rows),
    kill: (sessionId) => invoke('sessions:kill', sessionId),
    rename: (sessionId, title) => invoke('sessions:rename', sessionId, title),
    list: () => invoke('sessions:list'),
    onData: (handler) => subscribe<PtyDataEvent>('pty:data', handler),
    onExit: (handler) => subscribe<PtyExitEvent>('pty:exit', handler),
    watchActivity: (ccSessionId) => invoke('session:activity:watch', ccSessionId),
    unwatchActivity: (ccSessionId) => invoke('session:activity:unwatch', ccSessionId),
    onActivity: (handler) => subscribe<SessionActivity>('session:activity', handler),
    listLiveGlobal: () => invoke('sessions:list-live-global'),
    listEndedGlobal: () => invoke('sessions:list-ended-global'),
    watchGlobalActivity: () => {
      void invoke('session:activity:watch-global')
    },
    unwatchGlobalActivity: () => {
      void invoke('session:activity:unwatch-global')
    },
    onGlobalActivity: (handler) =>
      subscribe<GlobalActivityBatch>('session:activity:global', handler),
    setRendererFocus: (ccSessionId) => {
      void invoke('sessions:renderer-focus', ccSessionId)
    },
  },
  chat: {
    getTranscript: (sessionId) => invoke('chat:get-transcript', sessionId),
    readPlanFile: (path) => invoke('chat:read-plan-file', path),
    watch: (sessionId) => {
      void invoke('chat:watch', sessionId)
    },
    unwatch: (sessionId) => {
      void invoke('chat:unwatch', sessionId)
    },
    onTranscriptUpdate: (handler) =>
      subscribe<ChatTranscriptUpdate>('chat:transcript-update', handler),
  },
  shell: {
    openPath: (path: string) => invoke('shell:open-path', path),
    openExternal: (url: string) => invoke('shell:open-external', url),
  },
  app: {
    getInfo: () => invoke('app:get-info'),
  },
  gpu: {
    status: () => invoke('gpu:status'),
    setDisabled: (disabled: boolean) => invoke('gpu:set-disabled', disabled),
    setOzone: (ozone: boolean) => invoke('gpu:set-ozone', ozone),
    relaunch: () => invoke('app:relaunch'),
    onResumed: (handler) => subscribe('gpu:resumed', handler),
    onCrashed: (handler) => subscribe('gpu:crashed', handler),
  },
  dialog: {
    openDirectory: () => invoke('dialog:open-directory'),
  },
  prefs: {
    get: <T>(key: string) => invoke<T | null>('prefs:get', { key }),
    set: (key: string, value: unknown) => invoke('prefs:set', { key, value }),
  },
  voice: {
    transcribe: (bytes: Uint8Array, mime: string) => invoke('voice:transcribe', { bytes, mime }),
    condense: (text: string) => invoke('voice:condense', { text }),
    configStatus: () => invoke('voice:config-status'),
    onSummary: (handler) => subscribe<VoiceSummaryEvent>('voice:summary', handler),
  },
  secrets: {
    status: () => invoke('secrets:env:status'),
    list: () => invoke('secrets:env:list'),
    reveal: (key: string) => invoke('secrets:env:reveal', { key }),
    set: (key: string, value: string) => invoke('secrets:env:set', { key, value }),
    remove: (key: string) => invoke('secrets:env:delete', { key }),
    rename: (from: string, to: string) => invoke('secrets:env:rename', { from, to }),
  },
  vault: {
    getRoot: () => invoke('vault:get-root'),
    isConfigured: () => invoke('vault:is-configured'),
    setRoot: (root: string) => invoke('vault:set-root', { root }),
    ensureDir: (path: string) => invoke('vault:ensure-dir', { path }),
    isInside: (vaultPath: string, target: string) =>
      invoke('vault:is-inside', { vaultPath, target }),
    listUntracked: (projectId: string) => invoke('vault:list-untracked', { projectId }),
  },
  fs: {
    listDir: (path: string) => invoke('fs:list-dir', { path }),
    readFile: (path: string) => invoke('fs:read-file', { path }),
    writeFile: (path: string, content: string) => invoke('fs:write-file', { path, content }),
  },
  repo: {
    moveIntoVault: (source: string, vaultPath: string, label: string) =>
      invoke('repo:move-into-vault', { source, vaultPath, label }),
    symlinkIntoVault: (source: string, vaultPath: string, label: string) =>
      invoke('repo:symlink-into-vault', { source, vaultPath, label }),
    removeSymlink: (target: string) => invoke('repo:remove-symlink', { target }),
    cloneUrl: (url: string, vaultPath: string) =>
      invoke('repo:clone-url', { url, vaultPath }),
    createBlank: (vaultPath: string, name: string, gitInit: boolean) =>
      invoke('repo:create-blank', { vaultPath, name, gitInit }),
    listMissing: () => invoke('repos:list-missing'),
    cloneMissing: () => invoke('repos:clone-missing'),
    pullAll: () => invoke('repos:pull-all'),
    pullOne: (selector: { repoId?: string; path?: string }) =>
      invoke('repos:pull-one', selector),
    lastPullRun: () => invoke('repos:last-run'),
  },
  workspace: {
    getActive: () => invoke('workspace:get-active'),
    setActive: (projectId: string | null) => invoke('workspace:set-active', { projectId }),
    savePanes: (panes: PaneSnapshot[]) => invoke('workspace:save-panes', { panes }),
    saveLayout: (layout: string | null) => invoke('workspace:save-layout', { layout }),
    getBootState: () => invoke('workspace:get-boot-state'),
    bumpRestoreAttempts: () => invoke('workspace:bump-restore-attempts'),
    resetRestoreAttempts: () => invoke('workspace:reset-restore-attempts'),
  },
  ccConfigs: {
    read: () => invoke('cc:read-configs'),
    listLauncherItems: () => invoke('cc:list-launcher-items'),
  },
  ccPlugins: {
    list: () => invoke('cc:plugins:list'),
    available: () => invoke('cc:plugins:available'),
    details: (name: string) => invoke('cc:plugins:details', { name }),
    action: (action, name) => invoke('cc:plugins:action', { action, name }),
  },
  ccSettings: {
    read: (scope) => invoke('cc:settings:read', scope),
    write: (input) => invoke('cc:settings:write', input),
    readClaudeMd: () => invoke('cc:claude-md:read'),
    writeClaudeMd: (content: string) => invoke('cc:claude-md:write', { content }),
    listRules: () => invoke('cc:rules:list'),
    readRule: (relPath: string) => invoke('cc:rules:read', { relPath }),
    listHooks: () => invoke('cc:hooks:list'),
    disableHook: (event, index, entry) => invoke('cc:hooks:disable', { event, index, entry }),
    enableHook: (event, disabledIndex) => invoke('cc:hooks:enable', { event, disabledIndex }),
    readKeybindings: () => invoke('cc:keybindings:read'),
    writeKeybindings: (content: string) => invoke('cc:keybindings:write', { content }),
    readStatuslineScript: () => invoke('cc:statusline-script:read'),
    writeStatuslineScript: (content: string) => invoke('cc:statusline-script:write', { content }),
  },
  updates: {
    onStatus: (handler) => subscribe<UpdateStatus>('update:status', handler),
    apply: () => invoke('updates:apply'),
    install: () => invoke('updates:install'),
    openRelease: () => invoke('updates:open-release'),
    openDownloads: () => invoke('updates:open-downloads'),
  },
  usage: {
    get: () => invoke('usage:get'),
    refresh: () => invoke('usage:refresh'),
    onStatus: (handler) => subscribe<UsageStatus>('usage:status', handler),
  },
  metrics: {
    get: (window: MetricsWindow) => invoke('metrics:get', window),
    refresh: () => invoke('metrics:refresh'),
    onProgress: (handler) => subscribe<MetricsScanProgress>('metrics:progress', handler),
  },
  features: {
    list: (projectId?: string) => invoke('features:list', projectId),
    listWithStats: (opts?: { includeArchived?: boolean; includeDrafts?: boolean }) =>
      invoke('features:list-with-stats', opts),
    get: (id: string) => invoke('features:get', id),
    create: (input: CreateFeatureInput) => invoke('features:create', input),
    update: (input: UpdateFeatureInput) => invoke('features:update', input),
    archive: (id: string) => invoke('features:archive', id),
    setRepos: (input: SetFeatureReposInput) => invoke('features:set-repos', input),
    setObjectiveLinks: (input: SetFeatureObjectiveLinksInput) =>
      invoke('features:set-objective-links', input),
    listObjectiveLinks: (featureId: string) => invoke('features:list-objective-links', featureId),
    backfill: () => invoke('features:backfill'),
    onUpdated: (handler) => subscribe<Feature>('feature:updated', handler),
    onSynthError: (handler) => subscribe<FeatureSynthError>('feature:synth-error', handler),
  },
  repoDeps: {
    list: (projectId: string) => invoke('repo-deps:list', projectId),
    listAll: () => invoke('repo-deps:list-all'),
    create: (input: CreateRepoDependencyInput) => invoke('repo-deps:create', input),
    update: (input: UpdateRepoDependencyInput) => invoke('repo-deps:update', input),
    delete: (input: { id: string; projectId: string }) => invoke('repo-deps:delete', input),
    setRepoPosition: (input: { repoId: string; x: number; y: number; projectId: string }) =>
      invoke('repos:set-position', input),
    setRepoHub: (input: SetRepoHubInput) => invoke('repos:set-hub', input),
    connectHubToAll: (input: ConnectHubToAllInput) =>
      invoke('repo-deps:connect-hub-to-all', input),
    onUpdated: (handler) => subscribe<{ projectId: string | null }>('repo-deps:updated', handler),
  },
  handoffs: {
    list: (opts?: { status?: HandoffStatus | HandoffStatus[] }) => invoke('handoffs:list', opts),
    get: (id: string) => invoke('handoffs:get', id),
    approve: (input: { id: string; composedPrompt?: string }) =>
      invoke('handoffs:approve', input),
    createManual: (input: CreateManualHandoffInput) => invoke('handoffs:create-manual', input),
    adoptSession: (input: AdoptSessionInput) => invoke('handoffs:adopt-session', input),
    reject: (id: string) => invoke('handoffs:reject', id),
    markRunning: (input: { id: string; childSessionId: string }) =>
      invoke('handoffs:mark-running', input),
    fail: (input: { id: string; error: string }) => invoke('handoffs:fail', input),
    sendMessage: (input: { id: string; text: string }) => invoke('handoffs:send-message', input),
    setOutcome: (input: { id: string; outcome: HandoffOutcome }) =>
      invoke('handoffs:set-outcome', input),
    dismiss: (id: string) => invoke('handoffs:dismiss', id),
    release: (id: string) => invoke('handoffs:release', id),
    resume: (id: string) => invoke('handoffs:resume', id),
    isResumable: (id: string) => invoke('handoffs:is-resumable', id),
    spawnContext: (id: string) => invoke('handoffs:spawn-context', id),
    onUpdated: (handler) => subscribe<unknown>('handoff:updated', handler),
  },
  baton: {
    distill: (input: DistillBatonInput) => invoke('baton:distill', input),
    pass: (input: PassBatonInput) => invoke('baton:pass', input),
  },
  dossiers: {
    create: (input: CreateDossierApiInput) => invoke('dossiers:create', input),
    list: (opts?: { status?: DossierStatus }) => invoke('dossiers:list', opts),
    get: (id: string) => invoke('dossiers:get', id),
    archive: (id: string) => invoke('dossiers:archive', id),
    startRun: (input: { dossierId: string }) => invoke('dossiers:startRun', input),
    approveGateA: (input: { runId: string; plan?: DossierPlanInput }) =>
      invoke('dossiers:approveGateA', input),
    approveGateB: (input: { runId: string; keepEvidenceIds?: string[] }) =>
      invoke('dossiers:approveGateB', input),
    resumeRun: (input: { runId: string }) => invoke('dossiers:resumeRun', input),
    listRuns: (dossierId: string) => invoke('dossiers:listRuns', dossierId),
    getRun: (runId: string) => invoke('dossiers:getRun', runId),
    listEvidence: (runId: string) => invoke('dossiers:listEvidence', runId),
    listSources: (runId: string) => invoke('dossiers:listSources', runId),
    isWebSearchEnabled: () => invoke('dossiers:isWebSearchEnabled'),
    onRunUpdated: (handler) => subscribe<unknown>('dossier:run-updated', handler),
    onUpdated: (handler) => subscribe<unknown>('dossier:updated', handler),
  },
  objectives: {
    list: (filter?: ObjectiveListFilter) => invoke('objectives:list', filter),
    get: (id: string) => invoke('objectives:get', id),
    overview: () => invoke('objectives:overview'),
    create: (input: CreateObjectiveInput) => invoke('objectives:create', input),
    update: (input: UpdateObjectiveInput) => invoke('objectives:update', input),
    archive: (id: string) => invoke('objectives:archive', id),
    createKeyResult: (input: CreateKeyResultInput) => invoke('objectives:kr-create', input),
    updateKeyResult: (input: UpdateKeyResultInput) => invoke('objectives:kr-update', input),
    deleteKeyResult: (id: string) => invoke('objectives:kr-delete', id),
    onUpdated: (handler) => subscribe<unknown>('objective:updated', handler),
  },
  tasks: {
    list: (filter?: TaskListFilter) => invoke('tasks:list', filter),
    get: (id: string) => invoke('tasks:get', id),
    listByParent: (parentType: TaskParentType, parentId: string) =>
      invoke('tasks:list-by-parent', parentType, parentId),
    create: (input: CreateTaskInput) => invoke('tasks:create', input),
    update: (input: UpdateTaskInput) => invoke('tasks:update', input),
    delete: (id: string) => invoke('tasks:delete', id),
    setLinks: (taskId: string, links: TaskLink[]) => invoke('tasks:set-links', taskId, links),
    reorder: (taskId: string, position: number) => invoke('tasks:reorder', taskId, position),
    onUpdated: (handler) => subscribe<unknown>('task:updated', handler),
  },
  scheduledJobs: {
    list: (filter?: ScheduledJobListFilter) => invoke('scheduledJobs:list', filter),
    get: (id: string) => invoke('scheduledJobs:get', id),
    create: (input: CreateScheduledJobInput) => invoke('scheduledJobs:create', input),
    update: (input: UpdateScheduledJobInput) => invoke('scheduledJobs:update', input),
    delete: (id: string) => invoke('scheduledJobs:delete', id),
    listRuns: (filter?: JobRunListFilter) => invoke('scheduledJobs:list-runs', filter),
    runNow: (id: string) => invoke('scheduledJobs:run-now', id),
    previewRuns: (schedule: JobSchedule, count: number) =>
      invoke('scheduledJobs:preview-runs', schedule, count),
    onUpdated: (handler) => subscribe<unknown>('scheduledJob:updated', handler),
    onRunUpdated: (handler) => subscribe<unknown>('jobRun:updated', handler),
  },
  contentContracts: {
    list: (filter?: ContentContractListFilter) => invoke('contentContracts:list', filter),
    get: (id: string) => invoke('contentContracts:get', id),
    upsert: (input: UpsertContentContractInput) => invoke('contentContracts:upsert', input),
    listVersions: (contractId: string) => invoke('contentContracts:list-versions', contractId),
    listGateRuns: (filter?: ContentGateRunListFilter) =>
      invoke('contentContracts:list-gate-runs', filter),
    runGate: (input: RunContentGateInput) => invoke('contentContracts:run-gate', input),
    onUpdated: (handler) => subscribe<unknown>('contentContract:updated', handler),
    onGateRunUpdated: (handler) => subscribe<unknown>('contentGateRun:updated', handler),
  },
  diagrams: {
    list: (filter?: DiagramListFilter) => invoke('diagrams:list', filter),
    get: (id: string) => invoke('diagrams:get', id),
    create: (input: CreateDiagramInput) => invoke('diagrams:create', input),
    updateScene: (input: UpdateDiagramSceneInput) => invoke('diagrams:update-scene', input),
    rename: (id: string, title: string) => invoke('diagrams:rename', id, title),
    archive: (id: string) => invoke('diagrams:archive', id),
    unarchive: (id: string) => invoke('diagrams:unarchive', id),
    delete: (id: string) => invoke('diagrams:delete', id),
    link: (input: DiagramLink) => invoke('diagrams:link', input),
    unlink: (input: DiagramLink) => invoke('diagrams:unlink', input),
    listVersions: (diagramId: string) => invoke('diagrams:list-versions', diagramId),
    getVersion: (diagramId: string, version: number) =>
      invoke('diagrams:get-version', diagramId, version),
    restoreVersion: (diagramId: string, version: number, author?: DiagramAuthor) =>
      invoke('diagrams:restore-version', diagramId, version, author),
    setThumbnail: (id: string, dataUrl: string) => invoke('diagrams:set-thumbnail', id, dataUrl),
    onUpdated: (handler) => subscribe<unknown>('diagram:updated', handler),
    onDeleted: (handler) => subscribe<unknown>('diagram:deleted', handler),
    onLinksUpdated: (handler) => subscribe<unknown>('diagramLinks:updated', handler),
  },
  meetings: {
    list: (filter?: MeetingListFilter) => invoke('meetings:list', filter),
    get: (id: string) => invoke('meetings:get', id),
    create: (input: CreateMeetingInput) => invoke('meetings:create', input),
    update: (input: UpdateMeetingInput) => invoke('meetings:update', input),
    delete: (id: string) => invoke('meetings:delete', id),
    listSegments: (meetingId: string) => invoke('meetings:list-segments', meetingId),
    listSpeakers: (meetingId: string) => invoke('meetings:list-speakers', meetingId),
    setSpeakerName: (input: SetSpeakerNameInput) => invoke('meetings:set-speaker-name', input),
    search: (query: string) => invoke('meetings:search', query),
    sidecarConfigured: () => invoke<boolean>('meetings:sidecar-configured'),
    installSidecar: () => invoke('meetings:install-sidecar'),
    startCapture: (meetingId: string) => invoke('meetings:start-capture', meetingId),
    stopCapture: (meetingId: string) => invoke('meetings:stop-capture', meetingId),
    extract: (meetingId: string) => invoke('meetings:extract', meetingId),
    materializeTask: (input: MaterializeMeetingTaskInput) =>
      invoke('meetings:materialize-task', input),
    onUpdated: (handler) => subscribe<unknown>('meeting:updated', handler),
    onTranscriptSegment: (handler) =>
      subscribe<MeetingSegment>('meeting:transcript:segment', handler),
    onTranscriptPartial: (handler) =>
      subscribe<MeetingPartialEvent>('meeting:transcript:partial', handler),
    onStatus: (handler) => subscribe<MeetingStatusEvent>('meeting:status', handler),
    onInstallLog: (handler) => subscribe<MeetingInstallLogEvent>('meeting:install:log', handler),
    onInstallDone: (handler) =>
      subscribe<MeetingInstallDoneEvent>('meeting:install:done', handler),
    onSpeaker: (handler) => subscribe<MeetingSpeaker>('meeting:speaker', handler),
    onCalendarActivate: (handler) =>
      subscribe<MeetingActivationDraft>('meeting:calendar:activate', handler),
  },
  notifications: {
    onEvent: (handler) => subscribe<NotificationEvent>('notify:event', handler),
    onOpenSession: (handler) => subscribe<string>('notify:open-session', handler),
  },
  mcp: {
    status: () => invoke('mcp:status'),
    listServers: () => invoke('cc:mcp:list'),
    addServer: (input: McpAddInput) => invoke('cc:mcp:add', input),
    removeServer: (input: McpRemoveInput) => invoke('cc:mcp:remove', input),
  },
  sync: {
    status: () => invoke('sync:status'),
    configure: (input: SyncConfigureInput) => invoke('sync:configure', input),
    setProjectsRoot: (input: SyncSetProjectsRootInput) => invoke('sync:set-projects-root', input),
    now: () => invoke('sync:now'),
    exportForce: () => invoke('sync:export-force'),
    importForce: () => invoke('sync:import-force'),
    resolveConflict: (input: SyncResolveConflictInput) => invoke('sync:resolve-conflict', input),
    backupExport: () => invoke('sync:backup-export'),
    backupImport: () => invoke('sync:backup-import'),
  },
  window: {
    minimize: () => invoke('window:minimize'),
    toggleMaximize: () => invoke('window:toggle-maximize'),
    close: () => invoke('window:close'),
    isMaximized: () => invoke('window:is-maximized'),
    onMaximizeChange: (handler) => subscribe<boolean>('window:maximize-changed', handler),
  },
}

contextBridge.exposeInMainWorld('api', api)
