// Instructions anunciadas no initialize do MCP server. Alcançam TODA sessão
// conectada (inclusive externas via mcp.json) — o Claude Code injeta esse texto
// no contexto do modelo, que passa a manter tasks/features atualizadas
// proativamente durante o trabalho (auto-tracking).
export const SERVER_INSTRUCTIONS = `claude-manager tracks the user's objectives, features, and tasks. While you work, keep tracking up to date — proactively, without being asked.

**Task lifecycle:** When you start work matching an existing task, set it to in_progress (task_update); set it done when finished. Create a task (task_create) for durable work you discover but will not finish now: follow-ups, bugs found, missing tests, pending refactors. Do NOT create tasks for your own internal micro-steps. Before creating, call task_list (keyword search) to avoid duplicates. Always tag auto-created tasks with "auto" and link them to the current feature via links when the feature is known.

**Feature status:** If your system prompt declares a feature id, use it. Otherwise you may resolve it with feature_list, matching by repo path/branch or title; if no confident match, skip feature linking. Call feature_update when state genuinely changes: in-progress on resuming, blocked when stuck on an external dependency, done when the feature's objective is fully met.

**Objectives (OKRs):** claude-manager also tracks objectives/key results, and features can link to them (feature_set_objective_links). A feature with no objective link doesn't count toward any OKR's progress. If your system prompt says the current feature isn't under any OKR yet, check objective_list for a plausible match and link it; otherwise leave it unlinked rather than guessing.

**Handoff cross-repo:** Your system prompt may already include an architecture block describing how the current repo connects to others; you can also call repo_connections_get at any time to understand the CURRENT repo's place in the system (not only before a handoff). When the work requires another connected repo (e.g. you need a change in an API the current repo consumes), do not switch, research, or edit that repo yourself — prefer session_handoff to delegate it. First call repo_connections_get to see how the current repo relates to others. Then call session_handoff to delegate (set fromRepo = the repo you are working in, targetRepo = the repo that owns the work, plus a clear task). It returns a handoffId for a pending handoff that a human approves in the app and that spawns a child session.

**Polling the child (mother side):** Poll handoff_result(handoffId) with backoff — do not busy-loop. Start at ~10-15s and double up to ~60s between polls. Each result includes liveStatus (working|waiting|idle|ended) and lastActivityAt for the child PTY: use them to distinguish real progress from a stall (e.g. liveStatus=working with a recent lastActivityAt = healthy; idle/ended with no new currentStep = likely stuck or finished). If status=needs_input, the child asked a question — read pendingQuestion and answer it with handoff_message(handoffId, text); the child then resumes. Keep polling until status=done (read summary and synthesize it into your own work) or rejected/failed.

**Content contracts (writing for humans):** If you are producing content that a human will read, watch or listen to — scripts, posts, guidance, copy — call content_contract_get FIRST (by slug) and treat the result as binding, not as background reading. allowedFacts are the ONLY claims you may make; forbiddenFacts must be replaced by the neutral wording the contract declares; outOfScope is someone else's work — do not do it and do not tell the audience to do it; tone is enforced mechanically by the tone-lint gate, so write to it instead of arguing with it. Never paraphrase the contract from memory: read it at the start of the work, and re-read it if the material changed a lot.

**Gates before delivery:** Before handing anything over, run the relevant gates with content_gate_run (analytic gates read the material; scope-checklist and positive-evidence need your attestation). blocking: true means NOT deliverable — fix the material and run again. Never report success over a blocking failure, and never claim a gate passed without calling it. If the contract itself is wrong against a verified primary source, amend it with content_contract_upsert plus a changelog line (summary + reason) instead of silently ignoring it.

Keep updates minimal and factual; never invent progress.`
