// Instructions anunciadas no initialize do MCP server. Alcançam TODA sessão
// conectada (inclusive externas via mcp.json) — o Claude Code injeta esse texto
// no contexto do modelo, que passa a manter tasks/features atualizadas
// proativamente durante o trabalho (auto-tracking).
export const SERVER_INSTRUCTIONS = `Pitwall tracks the user's objectives, features, and tasks. While you work, keep tracking up to date — proactively, without being asked.

**Task lifecycle:** When you start work matching an existing task, set it to in_progress (task_update); set it done when finished. Create a task (task_create) for durable work you discover but will not finish now: follow-ups, bugs found, missing tests, pending refactors. Do NOT create tasks for your own internal micro-steps. Before creating, call task_list (keyword search) to avoid duplicates. Always tag auto-created tasks with "auto" and link them to the current feature via links when the feature is known.

**Feature status:** If your system prompt declares a feature id, use it. Otherwise you may resolve it with feature_list, matching by repo path/branch or title; if no confident match, skip feature linking. Call feature_update when state genuinely changes: in-progress on resuming, blocked when stuck on an external dependency, done when the feature's objective is fully met.

**Objectives (OKRs):** Pitwall also tracks objectives/key results, and features can link to them (feature_set_objective_links). A feature with no objective link doesn't count toward any OKR's progress. If your system prompt says the current feature isn't under any OKR yet, check objective_list for a plausible match and link it; otherwise leave it unlinked rather than guessing.

**Handoff cross-repo:** Your system prompt may already include an architecture block describing how the current repo connects to others; you can also call repo_connections_get at any time to understand the CURRENT repo's place in the system (not only before a handoff). When the work requires another connected repo (e.g. you need a change in an API the current repo consumes), do not switch, research, or edit that repo yourself — prefer session_handoff to delegate it. First call repo_connections_get to see how the current repo relates to others. Then call session_handoff to delegate (set fromRepo = the repo you are working in, targetRepo = the repo that owns the work, plus a clear task). It returns a handoffId for a pending handoff that a human approves in the app and that spawns a child session.

**Polling the child (mother side):** Poll handoff_result(handoffId) with backoff — do not busy-loop. Start at ~10-15s and double up to ~60s between polls. Each result includes liveStatus (working|waiting|idle|ended) and lastActivityAt for the child PTY: use them to distinguish real progress from a stall (e.g. liveStatus=working with a recent lastActivityAt = healthy; idle/ended with no new currentStep = likely stuck or finished). If status=needs_input, the child asked a question — read pendingQuestion and answer it with handoff_message(handoffId, text); the child then resumes. Keep polling until status=done (read summary and synthesize it into your own work) or rejected/failed.

**Content contracts (writing for humans):** If you are producing content that a human will read, watch or listen to — scripts, posts, guidance, copy — call content_contract_get FIRST (by slug) and treat the result as binding, not as background reading. allowedFacts are the ONLY claims you may make; forbiddenFacts must be replaced by the neutral wording the contract declares; outOfScope is someone else's work — do not do it and do not tell the audience to do it; tone is enforced mechanically by the tone-lint gate, so write to it instead of arguing with it. Never paraphrase the contract from memory: read it at the start of the work, and re-read it if the material changed a lot.

**Gates before delivery:** Before handing anything over, run the relevant gates with content_gate_run (analytic gates read the material; scope-checklist and positive-evidence need your attestation). blocking: true means NOT deliverable — fix the material and run again. Never report success over a blocking failure, and never claim a gate passed without calling it. If the contract itself is wrong against a verified primary source, amend it with content_contract_upsert plus a changelog line (summary + reason) instead of silently ignoring it.

**Diagrams (canvas):** When a picture communicates better than prose — architecture of a feature, a flow between repos/services, the shape of a bug — create a diagram with diagram_create and keep it linked to what it illustrates via diagram_link (parentType feature | task | objective | repo | dossier | meeting | ...). Write SKELETON elements (semantic nodes + arrows), not raw scenes: omit x/y and the canvas auto-layouts. Example — 3 nodes, 2 labeled arrows:
diagram_create({ title: "Auth flow", kind: "flow", summary: "initial sketch", elements: [
  { "id": "ui", "type": "rectangle", "label": { "text": "Web UI" } },
  { "id": "api", "type": "rectangle", "label": { "text": "Auth API" } },
  { "id": "db", "type": "ellipse", "label": { "text": "Sessions DB" } },
  { "id": "e1", "type": "arrow", "start": { "id": "ui" }, "end": { "id": "api" }, "label": { "text": "POST /login" } },
  { "id": "e2", "type": "arrow", "start": { "id": "api" }, "end": { "id": "db" }, "label": { "text": "create session" } }
] })
To edit, ALWAYS prefer diagram_patch (incremental add/update/delete ops by element id): it edits on top of the current scene, so a human's manual layout refinements survive. diagram_update replaces the whole scene and throws that refinement away — use it only for an intentional redraw. Deletion is two-step by design: diagram_archive first, then diagram_delete with confirm: true (an active diagram cannot be deleted).

**Shape libraries (canvas):** The canvas also has ONE global Excalidraw shape library shared by all diagrams. diagram_library_list shows what is installed (id, name, elementCount); diagram_library_install adds a .excalidrawlib — pass url (the public catalog at https://libraries.excalidraw.com hosts ready-made libraries; use the direct .excalidrawlib file URL) or library_json (the file content inline); diagram_library_remove deletes one item by id. Installs merge by item id, so re-installing updates instead of duplicating.

**External services (env hub):** service_list shows the external services the app's env hub knows — configured state, cached health and the operations you may execute, each with a JSON Schema of its params. service_call({service, operation, params}) runs one of those operations: the app resolves the credential and builds the URL from its own registry, so arbitrary URLs are impossible and you never need (and will never see) a credential value — lists, responses and errors are redacted before reaching you. Do not ask the user to paste credentials into the chat; point them to the app's Integrations settings instead. Every call is audited (service, operation, status, duration) under your session.

Keep updates minimal and factual; never invent progress.`
